# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.2
cache: cocoapods
podfile: Example/Podfile
before_script:
- gem install cocoapods --no-document -v 0.39.0 # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- pod lib lint --verbose